In [3]:
import gym
from stable_baselines import DQN
from stable_baselines.deepq.policies import MlpPolicy

In [4]:
#Descobrindo o escopo de ações que um agente pode ter no ambiente
env=gym.make('Acrobot-v1')
print(env.action_space)
print(env.action_space.n)

Discrete(3)
3


In [5]:
#Gerando ações aleatorias
for i in range(10):
    print(env.action_space.sample())

0
2
1
0
2
0
0
0
2
1


In [6]:
env=gym.make('Acrobot-v1') #cria um ambiente
obs=env.reset()
print(obs)

[ 0.99972392  0.02349666  0.99773815  0.06722036  0.08843709 -0.0374752 ]


In [7]:
#Os 6 valores que representam o estado do robô consistem no seno e cosseno dos angulos e velocidades
#angulares dos braços roboticos.
#As 3 ações consistem em aplicar um torque de +1, 0 ou -1 na junção movel entre os dois braços.
#O objetivo é fazer o braço do robo tocar na linha superior da figura
# A cada timestep, a recompensa obtida é sempre -1, exceto se o objetivo é antingido, recebendo
# zero neste caso.

In [10]:
import time
env=gym.make('Acrobot-v1')
obs=env.reset() #ate aqui temos somente o estado inicial do ambiente definido
lista_recompensas=[]
for i in range(1000):
    env.render()
    time.sleep(0.1)
    acao=env.action_space.sample() #gera uma nova ação aleatoria
    print(obs)
    obs, recompensa, terminou, info, = env.step(acao) #a partir de cada ação, vai para um novo
    # estado, recebe recompensa, diz se o episodio terminou (done) e traz um dicionario com 
    # outras informações, se houver.
    lista_recompensas.append(recompensa)
    if terminou: #se terminou um episodio
        print('Episodio finalizado depois de {} timesteps'.format(i+1))
        break
env.close() # fecha a janela

Exception ignored in: <function Viewer.__del__ at 0x00000277F11CF798>
Traceback (most recent call last):
  File "C:\Users\Falcone\anaconda3\envs\gymoa\lib\site-packages\gym\envs\classic_control\rendering.py", line 185, in __del__
    self.close()
  File "C:\Users\Falcone\anaconda3\envs\gymoa\lib\site-packages\gym\envs\classic_control\rendering.py", line 101, in close
    self.window.close()
  File "C:\Users\Falcone\anaconda3\envs\gymoa\lib\site-packages\pyglet\window\win32\__init__.py", line 332, in close
    super(Win32Window, self).close()
  File "C:\Users\Falcone\anaconda3\envs\gymoa\lib\site-packages\pyglet\window\__init__.py", line 858, in close
    app.windows.remove(self)
  File "C:\Users\Falcone\anaconda3\envs\gymoa\lib\_weakrefset.py", line 109, in remove
    self.data.remove(ref(item))
KeyError: (<weakref at 0x00000277F38C1C78; to 'Win32Window' at 0x00000277F0D26288>,)
Exception ignored in: <function Viewer.__del__ at 0x00000277F11CF798>
Traceback (most recent call last):
  F

[ 0.99850822  0.05460166  0.99916623 -0.04082713 -0.08482891 -0.03859355]
[ 0.99952161  0.03092809  0.99921622 -0.03958462 -0.14721033  0.04704672]
[ 0.99993342  0.01153928  0.99827202 -0.05876209 -0.04359053 -0.23835862]
[ 0.9999173  -0.01286075  0.99797263 -0.06364457 -0.19533978  0.18602365]
[ 0.99933649 -0.03642222  0.99832345 -0.05788161 -0.0356264  -0.13252345]
[ 0.9985787  -0.05329715  0.99890288 -0.04682977 -0.12935738  0.23833706]
[ 0.99826297 -0.05891558  0.99935087 -0.03602563  0.0742825  -0.13243936]
[ 0.99968418 -0.02513028  0.99529036 -0.09693859  0.25482952 -0.46178851]
[ 0.99970237  0.02439604  0.98439924 -0.17594923  0.22815141 -0.31500513]
[ 0.99810304  0.06156561  0.97678167 -0.21423719  0.13541776 -0.06357392]
[ 0.99801706  0.06294402  0.98630797 -0.1649139  -0.12041568  0.55766499]
[ 0.99907319  0.04304371  0.99754726 -0.06999618 -0.07174904  0.3788476 ]
[ 0.99972971  0.02324889  0.99990474  0.01380278 -0.11959586  0.44206891]
[ 0.99988904 -0.01489666  0.99113234  

[ 0.9330101  -0.35985018  0.89002987  0.45590221  1.90040707 -3.59904882]
[ 0.99937329  0.03539805  0.96425995 -0.264958    2.01099103 -3.56979718]
[ 0.91541089  0.40252068  0.60012253 -0.79990809  1.6889164  -2.86185595]
[ 0.77935935  0.62657721  0.21539729 -0.9765265   0.90951773 -1.38943217]
[ 0.72419261  0.68959776  0.11233742 -0.99367012 -0.08039969  0.33836467]
[ 0.78788238  0.61582575  0.2963574  -0.95507711 -0.88411713  1.54324926]
[ 0.91913009  0.39395417  0.68577579 -0.72781287 -1.66887012  2.98030093]
[ 0.99997749  0.00670987  0.99690187 -0.07865536 -2.21320872  4.19556253]
[ 0.91717122 -0.39849336  0.7566474   0.65382315 -1.83208873  3.48067005]
[ 0.76073367 -0.64906416  0.27547281  0.96130886 -1.0899072   2.2619426 ]
[ 0.67647539 -0.73646524 -0.01838071  0.99983106 -0.1200403   0.72322955]
[ 0.72174879 -0.6921551  -0.03668952  0.99932671  0.74108233 -0.54097896]
[ 0.86197586 -0.50694933  0.22248932  0.97493513  1.55634908 -2.07256518]
[ 0.98584907 -0.16763536  0.68825419  

[ 0.62414681 -0.78130708  0.8018145   0.59757302  1.06763323 -1.22438368]
[ 0.83375284 -0.55213785  0.96198748  0.27309355  2.00016027 -2.35401752]
[ 0.99320845 -0.11634848  0.96032394 -0.27888693  2.56914258 -3.03234539]
[ 0.93390998  0.35750824  0.71319182 -0.70096892  2.15004399 -1.75986231]
[ 0.74285682  0.66945033  0.52774587 -0.84940232  1.46508268 -0.58448342]
[ 0.60428335  0.7967695   0.55693625 -0.83055524  0.39178516  0.91725525]
[ 0.63311692  0.77405618  0.7930105  -0.60920796 -0.75335766  2.3095427 ]
[ 0.80717558  0.59031143  0.99715388 -0.07539324 -1.72588315  3.37903587]
[ 0.9760402   0.21759028  0.79308043  0.60911693 -2.28317979  3.69206869]
[ 0.97148152 -0.23711528  0.25220325  0.96767428 -2.22299468  2.7850801 ]
[ 0.80090942 -0.59878552 -0.16967101  0.98550076 -1.74020789  1.44138526]
[ 0.61840671 -0.78585822 -0.29138536  0.95660576 -0.83499589 -0.18445766]
[ 0.57876124 -0.81549704 -0.07438174  0.99722984  0.36517004 -2.03772317]
[ 0.71684618 -0.69723134  0.45912185  

[ 0.97083983  0.23972908  0.92609845 -0.37728195  1.63251261 -3.01973258]
[ 0.87136698  0.49063183  0.62947467 -0.777021    1.02173522 -1.92643424]
[ 0.79668308  0.60439728  0.38884397 -0.92130362  0.32183599 -0.86969662]
[ 0.81459582  0.58002901  0.38095494 -0.9245936  -0.61717516  0.78316243]
[ 0.90908264  0.41661584  0.60870833 -0.79339408 -1.24377728  1.82960495]
[ 0.99199577  0.12627111  0.9063334  -0.42256332 -1.72755661  2.88143061]
[ 0.97137645 -0.23754537  0.97851648  0.20616859 -1.83209791  3.35383713]
[ 0.84572151 -0.53362451  0.68139971  0.73191149 -1.32058228  2.64226109]
[ 0.73269518 -0.68055696  0.32828796  0.94457769 -0.51178999  1.48476474]
[ 0.72858943 -0.68495069  0.18392305  0.98294065  0.44475254  0.01194365]
[ 0.83269214 -0.55373621  0.29908298  0.95422711  1.20534839 -1.1962507 ]
[ 0.9647122  -0.2633066   0.65591676  0.75483323  1.95496429 -2.89536507]
[ 0.98966258  0.14341539  0.9782237   0.20755336  2.04816851 -3.38264157]
[ 0.87475997  0.48455649  0.91900293 -

[ 0.99813732  0.06100736  0.98823684 -0.15293116  2.67926268 -3.03055395]
[ 0.85493208  0.51873995  0.79725146 -0.60364734  2.06077006 -1.76321929]
[ 0.63718501  0.77071088  0.62715906 -0.77889121  1.23531741 -0.65991097]
[ 0.53698391  0.84359249  0.65737198 -0.75356624 -0.01095225  1.03948425]
[ 0.64154095  0.76708879  0.88644826 -0.4628277  -1.27131886  2.6630983 ]
[ 0.86484591  0.50203741  0.98884722  0.14893346 -2.13035536  3.48703988]
[ 0.9985585   0.0536742   0.65598064  0.75477771 -2.47882183  3.34199885]
[ 0.91079098 -0.41286775  0.15442662  0.98800426 -2.23276229  2.16610791]
[ 0.69627322 -0.71777684 -0.10892335  0.99405015 -1.45420937  0.47114274]
[ 0.5445932  -0.83870033 -0.06023165  0.99818443 -0.45412908 -0.94885468]
[ 0.56978653 -0.82179274  0.28855242  0.9574641   0.76794451 -2.58756797]
[ 0.77901441 -0.62700603  0.84649744  0.53239279  2.07279119 -4.55885733]
[ 0.97955459 -0.20117855  0.91956105 -0.39294717  2.51511187 -4.75565125]
[ 0.96390878  0.26623274  0.34620822 -

In [11]:
env=gym.make('Acrobot-v1')

modelo = DQN(policy=MlpPolicy, env=env, gamma=0.99, learning_rate=0.0005, buffer_size=5000, 
            exploration_fraction=0.1, exploration_final_eps=0.1, exploration_initial_eps=1.0, 
            batch_size=32, double_q=False, learning_starts=5000, verbose=1)
modelo.learn(total_timesteps=50000, log_interval=10)







Instructions for updating:
Use keras.layers.flatten instead.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where




--------------------------------------
| % time spent exploring  | 18       |
| episodes                | 10       |
| mean 100 episode reward | -500     |
| steps                   | 4500     |
--------------------------------------
--------------------------------------
| % time spent exploring  | 9        |
| episodes                | 20       |
| mean 100 episode reward | -360     |
| steps                   | 6857     |
--------------------------------------
--------------------------------------
| % time spent exploring  | 9        |
| episodes                | 30       |
| mean 100 episode reward | -307     |
| steps                   | 8909     |
--------------------------------------
--------------------------------------
| % time spent exploring  | 9        |
| episodes                | 40       |
| mean 100 episode reward | -290     |
| steps                   | 11323    |
--------------------------------------
--------------------------------------
| % time spent explorin

--------------------------------------
| % time spent exploring  | 9        |
| episodes                | 110      |
| mean 100 episode reward | -185     |
| steps                   | 23062    |
--------------------------------------
--------------------------------------
| % time spent exploring  | 9        |
| episodes                | 120      |
| mean 100 episode reward | -178     |
| steps                   | 24709    |
--------------------------------------
--------------------------------------
| % time spent exploring  | 9        |
| episodes                | 130      |
| mean 100 episode reward | -197     |
| steps                   | 28715    |
--------------------------------------
--------------------------------------
| % time spent exploring  | 9        |
| episodes                | 140      |
| mean 100 episode reward | -205     |
| steps                   | 31951    |
--------------------------------------
--------------------------------------
| % time spent exploring 

In [15]:
import time
# Visualizando o modelo treinado:
obs = env.reset()
terminou = False
recompensa_total = 0
for i in range(5):
    while terminou!= True:
        acao, estado = modelo.predict(obs)
        obs, recompensa, terminou, info = env.step(acao)
        recompensa_total+=recompensa
        env.render()
        time.sleep(0.05) 
    print('Recompensa total:', recompensa_total)
    obs=env.reset()
    recompensa_total=0
    terminou=False
    time.sleep(1)
env.close()

Recompensa total: -87.0
Recompensa total: -90.0
Recompensa total: -89.0
Recompensa total: -75.0
Recompensa total: -96.0
Recompensa total: -76.0
Recompensa total: -93.0
Recompensa total: -76.0
Recompensa total: -72.0
Recompensa total: -158.0
